#ddev-generated
# If you remove the ddev-generated line above you
# are responsible for maintaining this file. DDEV will not then
# update it, for example if you add `additional_hostnames`, etc.

http:
  routers:
    initial-test-of-platform-ci-with-lando-web-80-http:
      entrypoints:
        - http-8000
      rule: HostRegexp(`^initial-test-of-platform-ci-with-lando\.ddev\.site$`)
      
      service: "initial-test-of-platform-ci-with-lando-web-80"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "initial-test-of-platform-ci-with-lando-redirectHttps"
    initial-test-of-platform-ci-with-lando-web-8025-http:
      entrypoints:
        - http-8025
      rule: HostRegexp(`^initial-test-of-platform-ci-with-lando\.ddev\.site$`)
      
      service: "initial-test-of-platform-ci-with-lando-web-8025"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "initial-test-of-platform-ci-with-lando-redirectHttps"
    
    
    
    initial-test-of-platform-ci-with-lando-web-80-https:
      entrypoints:
        - http-8443
      rule: HostRegexp(`^initial-test-of-platform-ci-with-lando\.ddev\.site$`)
      
      service: "initial-test-of-platform-ci-with-lando-web-80"
      ruleSyntax: v3
      
      tls: true
      
    initial-test-of-platform-ci-with-lando-web-8025-https:
      entrypoints:
        - http-8026
      rule: HostRegexp(`^initial-test-of-platform-ci-with-lando\.ddev\.site$`)
      
      service: "initial-test-of-platform-ci-with-lando-web-8025"
      ruleSyntax: v3
      
      tls: true
      
    

  middlewares:
    initial-test-of-platform-ci-with-lando-redirectHttps:
      redirectScheme:
        scheme: https
        permanent: true

  services:
    initial-test-of-platform-ci-with-lando-web-80:
      loadbalancer:
        servers:
          - url: http://ddev-initial-test-of-platform-ci-with-lando-web:80
        
    initial-test-of-platform-ci-with-lando-web-8025:
      loadbalancer:
        servers:
          - url: http://ddev-initial-test-of-platform-ci-with-lando-web:8025
        
    
    
    

tls:
  certificates:
    - certFile: /mnt/ddev-global-cache/traefik/certs/initial-test-of-platform-ci-with-lando.crt
      keyFile: /mnt/ddev-global-cache/traefik/certs/initial-test-of-platform-ci-with-lando.key